name: Korean

on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checking this repository
        uses: actions/checkout@v2

      - name: Exporting the csv file
        uses: actions/upload-artifact@v2
        with:
          name: language-korean
          path: korean.csv
          if-no-files-found: error
