name: Making a single file archive.
on: [workflow_dispatch, release, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking this repository
        uses: actions/checkout@v2

      - name: Exporting the csv file
        uses: actions/upload-artifact@v2
        with:
          path: korean.csv, english.csv
          name: Processing ${{path}}
          if-no-files-found: error
          
